// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class change_ISBN_Lenght : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_ISBN_Lenght));
        
        string IMigrationMetadata.Id
        {
            get { return "202102011141074_change_ISBN_Lenght"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
