// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class change_field_of_stock : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_field_of_stock));
        
        string IMigrationMetadata.Id
        {
            get { return "202101310120164_change_field_of_stock"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
